const JSON_HEADERS = { 'content-type':'application/json; charset=utf-8', 'cache-control':'no-store' };
const COOKIE = 'uor_session';
const SESSION_DAYS = 30;
const RANKS = [
  ['soldado','Soldado',0],['cabo','Cabo',100],['terceiro_sargento','Terceiro Sargento',250],['segundo_sargento','Segundo Sargento',450],['primeiro_sargento','Primeiro Sargento',700],['aspirante','Aspirante',1000],['segundo_tenente','Segundo Tenente',1400],['primeiro_tenente','Primeiro Tenente',1900],['capitao','Capitão',2500],['major','Major',3300],['coronel','Coronel',4300],['tenente_coronel','Tenente Coronel',5600],['general_brigada','General de Brigada',7200],['general_divisao','General de Divisão',9200],['general_exercito','General de Exército',11500],['marechal','Marechal',14000]
];
const COLORS = ['crimson','azure','forest','brass','violet','ash'];
const CONTINENTS = {NA:{name:'América do Norte',bonus:5},SA:{name:'América do Sul',bonus:2},EU:{name:'Europa',bonus:4},AF:{name:'África',bonus:3},AS:{name:'Ásia',bonus:7},OC:{name:'Oceania',bonus:2}};
const TERRITORIES = [
 ['alaska','Alasca','NA'],['mackenzie','Mackenzie','NA'],['vancouver','Vancouver','NA'],['ottawa','Ottawa','NA'],['labrador','Labrador','NA'],['california','Califórnia','NA'],['nova_york','Nova York','NA'],['mexico','México','NA'],['groelandia','Groelândia','NA'],
 ['colombia_venezuela','Colômbia/Venezuela','SA'],['brasil','Brasil','SA'],['peru_bolivia_chile','Peru/Bolívia/Chile','SA'],['argentina_uruguai','Argentina/Uruguai','SA'],
 ['islandia','Islândia','EU'],['inglaterra','Inglaterra','EU'],['suecia','Suécia','EU'],['alemanha','Alemanha','EU'],['franca','França','EU'],['espanha','Espanha','EU'],['italia','Itália','EU'],['polonia','Polônia','EU'],['moscou','Moscou','EU'],
 ['argelia','Argélia','AF'],['libia','Líbia','AF'],['egito','Egito','AF'],['nigeria','Nigéria','AF'],['sudao','Sudão','AF'],['congo','Congo','AF'],['tanzania','Tanzânia','AF'],['africa_sul','África do Sul','AF'],['madagascar','Madagascar','AF'],
 ['dudinka','Dudinka','AS'],['omsk','Omsk','AS'],['siberia','Sibéria','AS'],['vladivostok','Vladivostok','AS'],['mongolia','Mongólia','AS'],['tchita','Tchita','AS'],['aral','Aral','AS'],['china','China','AS'],['oriente_medio','Oriente Médio','AS'],['india','Índia','AS'],['vietna','Vietnã','AS'],['japao','Japão','AS'],
 ['sumatra','Sumatra','OC'],['borneu','Bornéu','OC'],['nova_guine','Nova Guiné','OC'],['australia','Austrália','OC']
].map(([id,name,continent])=>({id,name,continent}));
const T = Object.fromEntries(TERRITORIES.map(t=>[t.id,t]));
const ADJ = {
 colombia_venezuela:['brasil','peru_bolivia_chile','mexico'],peru_bolivia_chile:['colombia_venezuela','brasil','argentina_uruguai'],brasil:['colombia_venezuela','peru_bolivia_chile','argentina_uruguai','nigeria'],argentina_uruguai:['peru_bolivia_chile','brasil'],
 alaska:['mackenzie','vladivostok','vancouver'],mackenzie:['alaska','vancouver','ottawa','groelandia'],vancouver:['mackenzie','ottawa','california','alaska'],ottawa:['mackenzie','vancouver','labrador','nova_york','california'],labrador:['ottawa','nova_york','groelandia'],groelandia:['labrador','islandia','mackenzie'],california:['vancouver','nova_york','mexico','ottawa'],nova_york:['ottawa','labrador','california','mexico'],mexico:['california','nova_york','colombia_venezuela'],
 islandia:['groelandia','inglaterra'],inglaterra:['islandia','suecia','alemanha','franca'],suecia:['inglaterra','alemanha','polonia','moscou'],alemanha:['inglaterra','suecia','franca','polonia','italia'],franca:['inglaterra','alemanha','espanha','italia'],espanha:['franca','italia'],italia:['franca','polonia','alemanha','espanha','oriente_medio','argelia'],polonia:['suecia','alemanha','italia','moscou','oriente_medio'],moscou:['suecia','polonia','omsk','aral','oriente_medio'],
 argelia:['libia','nigeria','italia'],libia:['argelia','egito','nigeria','sudao'],egito:['libia','sudao','oriente_medio'],nigeria:['brasil','argelia','libia','sudao','congo'],sudao:['libia','egito','nigeria','congo','tanzania'],congo:['nigeria','sudao','tanzania','africa_sul'],tanzania:['sudao','congo','africa_sul','madagascar'],africa_sul:['congo','tanzania','madagascar'],madagascar:['tanzania','africa_sul'],
 dudinka:['omsk','mongolia','siberia'],omsk:['dudinka','mongolia','aral','moscou'],siberia:['dudinka','tchita','vladivostok','mongolia'],vladivostok:['siberia','tchita','japao','alaska'],tchita:['siberia','vladivostok','mongolia','china'],mongolia:['omsk','siberia','tchita','aral','china','dudinka'],aral:['omsk','mongolia','china','oriente_medio','moscou','india'],china:['mongolia','tchita','aral','india','vietna','japao'],oriente_medio:['moscou','aral','india','egito','polonia','italia'],india:['oriente_medio','aral','china','vietna','sumatra'],vietna:['china','india','borneu'],japao:['vladivostok','china'],
 australia:['sumatra','borneu','nova_guine'],nova_guine:['australia','borneu'],borneu:['nova_guine','vietna','australia'],sumatra:['australia','india']
};
const OBJECTIVE_POOL = [
 {type:'territories',count:24,text:'Conquistar 24 territórios quaisquer.'},{type:'territories',count:18,text:'Conquistar 18 territórios quaisquer.'},
 {type:'continents',list:['AS','AF'],text:'Dominar por completo a Ásia e a África.'},{type:'continents',list:['AS','SA'],text:'Dominar por completo a Ásia e a América do Sul.'},{type:'continents',list:['NA','AF'],text:'Dominar por completo a América do Norte e a África.'},{type:'continents',list:['NA','OC'],text:'Dominar por completo a América do Norte e a Oceania.'},
 {type:'continents_any_extra',list:['EU','OC'],extra:1,text:'Dominar a Europa, a Oceania e mais um continente qualquer.'},{type:'continents_any_extra',list:['EU','SA'],extra:1,text:'Dominar a Europa, a América do Sul e mais um continente qualquer.'},{type:'continents_any_extra',list:['NA','AS'],extra:1,text:'Dominar a América do Norte, a Ásia e mais um continente qualquer.'},{type:'eliminate',text:'Destruir por completo o exército {COLOR}.'}
];
const STARTING_ARMIES = {2:40,3:35,4:30,5:25,6:20};
const CARD_SYMBOLS = ['espada','castelo','cavalo','aviao'];
const TRADE_VALUES = [4,6,8,10,12,15];
const AIR = 'aviao';

function now(){return Date.now();}
function uuid(){return crypto.randomUUID();}
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}});}
function parseCookie(req,name){const s=req.headers.get('Cookie')||'';for(const p of s.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='));}return null;}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; ${maxAge==null?'':`Max-Age=${maxAge}; `}Path=/; HttpOnly; Secure; SameSite=Lax`}
function clearCookie(name){return `${name}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax`}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function ub64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function sha256(s){return b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),{name:'PBKDF2'},false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:ub64(salt),iterations:100000,hash:'SHA-256'},key,256);return b64(bits);}
function rankFor(points){let idx=0;for(let i=0;i<RANKS.length;i++)if(points>=RANKS[i][2])idx=i;const r=RANKS[idx],next=RANKS[idx+1];return {id:r[0],name:r[1],min:r[2],next:next?{id:next[0],name:next[1],min:next[2]}:null,progress:next?Math.max(0,Math.min(100,((points-r[2])/(next[2]-r[2]))*100)):100};}
async function body(req){try{return await req.json()}catch{return {}}}
async function authUser(req,env){const token=parseCookie(req,COOKIE);if(!token)return null;const th=await sha256(token);const row=await env.DB.prepare(`SELECT u.id,u.nick,u.login,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).bind(th,now()).first();return row||null;}
async function createSession(env,userId){const token=crypto.getRandomValues(new Uint8Array(32));const raw=b64(token);const th=await sha256(raw),ts=now(),exp=ts+SESSION_DAYS*86400000;await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,created_at,expires_at) VALUES(?,?,?,?,?)').bind(uuid(),userId,th,ts,exp).run();return raw;}
function validNick(v){return /^[\p{L}0-9 _-]{3,24}$/u.test(v);}
function validLogin(v){return /^[a-zA-Z0-9._-]{3,24}$/.test(v);}
function passwordScore(p){let n=0;if(p.length>=8)n++;if(/[A-Z]/.test(p))n++;if(/[a-z]/.test(p))n++;if(/[0-9]/.test(p))n++;if(/[^A-Za-z0-9]/.test(p))n++;return n;}
async function rateBlocked(env,login){const cutoff=now()-15*60000;const r=await env.DB.prepare('SELECT COUNT(*) c FROM auth_attempts WHERE login=? AND success=0 AND created_at>?').bind(login,cutoff).first();return Number(r?.c||0)>=7;}
async function logAttempt(env,login,success){await env.DB.prepare('INSERT INTO auth_attempts(login,success,created_at) VALUES(?,?,?)').bind(login,success?1:0,now()).run();}

async function apiAuthRegister(req,env){
  try{
    const b=await body(req);
    const nick=String(b.nick||'').trim();
    const login=String(b.login||'').trim().toLowerCase();
    const password=String(b.password||'');
    const confirm=String(b.confirmPassword??b.password2??'');
    if(!validNick(nick))return json({ok:false,error:'Nick inválido. Use 3 a 24 caracteres.'},400);
    if(!validLogin(login))return json({ok:false,error:'Login inválido.'},400);
    if(password.length<8||passwordScore(password)<4)return json({ok:false,error:'Senha fraca. Use pelo menos 8 caracteres, com maiúscula, minúscula, número e símbolo.'},400);
    if(password!==confirm)return json({ok:false,error:'As senhas não coincidem.'},400);
    const exists=await env.DB.prepare('SELECT id FROM users WHERE login=? OR nick=?').bind(login,nick).first();
    if(exists)return json({ok:false,error:'Login ou nick já está em uso.'},409);
    const id=uuid(),salt=b64(crypto.getRandomValues(new Uint8Array(16))),ph=await hashPassword(password,salt),ts=now();
    await env.DB.batch([
      env.DB.prepare('INSERT INTO users(id,nick,login,password_salt,password_hash,created_at) VALUES(?,?,?,?,?,?)').bind(id,nick,login,salt,ph,ts),
      env.DB.prepare('INSERT INTO user_stats(user_id) VALUES(?)').bind(id)
    ]);
    const token=await createSession(env,id);
    return json({ok:true,user:{id,nick,login},session:true},200,{'set-cookie':cookie(COOKIE,token)});
  }catch(e){
    return json({ok:false,error:'Não foi possível criar a conta no servidor.',detail:String(e?.message||e)},500);
  }
}
async function apiAuthLogin(req,env){const b=await body(req),login=String(b.login||'').trim().toLowerCase(),password=String(b.password||'');if(!validLogin(login))return json({ok:false,error:'Login inválido.'},400);if(await rateBlocked(env,login))return json({ok:false,error:'Muitas tentativas. Aguarde 15 minutos.'},429);const u=await env.DB.prepare('SELECT * FROM users WHERE login=?').bind(login).first();if(!u){await logAttempt(env,login,false);return json({ok:false,error:'Login ou senha incorretos.'},401);}const ph=await hashPassword(password,u.password_salt);if(ph!==u.password_hash){await logAttempt(env,login,false);return json({ok:false,error:'Login ou senha incorretos.'},401);}await logAttempt(env,login,true);await env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND expires_at<?').bind(u.id,now()).run();await env.DB.prepare('UPDATE users SET last_login_at=? WHERE id=?').bind(now(),u.id).run();const token=await createSession(env,u.id);return json({ok:true,user:{id:u.id,nick:u.nick,login:u.login}},200,{'set-cookie':cookie(COOKIE,token)});}
async function apiAuthMe(req,env){const u=await authUser(req,env);return u?json({ok:true,user:{id:u.id,nick:u.nick,login:u.login}}):json({ok:false,error:'Não autenticado.'},401);}
async function apiAuthLogout(req,env){const token=parseCookie(req,COOKIE);if(token){const th=await sha256(token);await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(th).run();}return json({ok:true},200,{'set-cookie':clearCookie(COOKIE)});}

async function getRoomDO(env,id){return env.UOR_ROOM.get(env.UOR_ROOM.idFromName(id));}
async function apiRooms(req,env){const staleBefore=now()-30*60*1000;await env.DB.prepare('DELETE FROM rooms WHERE game_active=0 AND updated_at<?').bind(staleBefore).run();const rows=await env.DB.prepare('SELECT id,name,max_players,host_user_id,players_json,game_active,updated_at,created_at FROM rooms ORDER BY updated_at DESC LIMIT 100').all();return json({ok:true,rooms:(rows.results||[]).map(roomPublic)});}
function roomPublic(r){let players=[];try{players=JSON.parse(r.players_json||'[]')}catch{}return {id:r.id,name:r.name,maxPlayers:r.max_players,hostConnId:r.host_user_id,players,gameActive:!!r.game_active,updatedAt:r.updated_at,createdAt:r.created_at};}
async function apiCreateRoom(req,env,user){const b=await body(req),name=String(b.name||'').trim().slice(0,48)||`Campanha de ${user.nick}`,max=Math.max(2,Math.min(6,Number(b.maxPlayers)||4)),color=COLORS.includes(b.color)?b.color:COLORS[0];const existing=await env.DB.prepare('SELECT id FROM rooms WHERE players_json LIKE ?').bind(`%${user.id}%`).first();if(existing)return json({ok:false,error:'Você já está em uma sala.'},409);const id=uuid(),ts=now(),player={id:user.id,connId:user.id,name:user.nick,color,eliminated:false};await env.DB.prepare('INSERT INTO rooms(id,name,max_players,host_user_id,players_json,updated_at,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,name,max,user.id,JSON.stringify([player]),ts,ts).run();const d=await getRoomDO(env,id);await d.fetch(new Request('https://uor-room/internal/init',{method:'POST',headers:{'content-type':'application/json','x-uor-user':user.id},body:JSON.stringify({id,name,maxPlayers:max,hostConnId:user.id,players:[player]})}));return json({ok:true,room:{id,name,maxPlayers:max,hostConnId:user.id,players:[player],gameActive:false,updatedAt:ts}});}
async function apiJoinRoom(req,env,user,roomId){const b=await body(req),color=COLORS.includes(b.color)?b.color:COLORS[0],d=await getRoomDO(env,roomId);const r=await d.fetch(new Request('https://uor-room/internal/join',{method:'POST',headers:{'content-type':'application/json','x-uor-user':user.id},body:JSON.stringify({userId:user.id,name:user.nick,color})}));if(!r.ok)return r;const data=await r.json();await syncRoomRow(env,roomId,data.room);return json({ok:true,room:data.room,assignedColor:data.assignedColor||color});}
async function apiLeaveRoom(req,env,user,roomId){const d=await getRoomDO(env,roomId);const r=await d.fetch(new Request('https://uor-room/internal/leave',{method:'POST',headers:{'content-type':'application/json','x-uor-user':user.id},body:'{}'}));if(!r.ok)return r;const data=await r.json();if(data.deleted){await env.DB.prepare('DELETE FROM rooms WHERE id=?').bind(roomId).run();}else await syncRoomRow(env,roomId,data.room);return json({ok:true});}
async function syncRoomRow(env,roomId,room){await env.DB.prepare('UPDATE rooms SET name=?,max_players=?,host_user_id=?,players_json=?,game_active=?,updated_at=? WHERE id=?').bind(room.name||'Sala',room.maxPlayers||4,room.hostConnId||room.players?.[0]?.id||null,JSON.stringify(room.players||[]),room.gameActive?1:0,now(),roomId).run();}
async function apiChat(req,env,user){if(req.method==='GET'){const rows=await env.DB.prepare('SELECT nick name,color,text,ts FROM chat_messages ORDER BY id DESC LIMIT 200').all();return json({ok:true,chat:(rows.results||[]).reverse()});}const b=await body(req),text=String(b.text||'').trim().slice(0,400);if(!text)return json({ok:false,error:'Mensagem vazia.'},400);const entry={name:user.nick,color:COLORS.includes(b.color)?b.color:COLORS[0],text,ts:now()};await env.DB.prepare('INSERT INTO chat_messages(user_id,nick,color,text,ts) VALUES(?,?,?,?,?)').bind(user.id,user.nick,entry.color,text,entry.ts).run();await env.DB.prepare('DELETE FROM chat_messages WHERE id NOT IN (SELECT id FROM chat_messages ORDER BY id DESC LIMIT 200)').run();return json({ok:true,entry});}

async function apiProfile(req,env,user){const s=await env.DB.prepare('SELECT * FROM user_stats WHERE user_id=?').bind(user.id).first();const r=rankFor(Number(s?.points||0));const pos=await env.DB.prepare('SELECT COUNT(*) c FROM user_stats WHERE points>?').bind(Number(s?.points||0)).first();const ach=await env.DB.prepare('SELECT a.id,a.name,a.description,ua.unlocked_at FROM user_achievements ua JOIN achievements a ON a.id=ua.achievement_id WHERE ua.user_id=? ORDER BY ua.unlocked_at').bind(user.id).all();return json({ok:true,user:{id:user.id,nick:user.nick,login:user.login},stats:{points:Number(s?.points||0),games:Number(s?.games||0),wins:Number(s?.wins||0),losses:Number(s?.losses||0),abandons:Number(s?.abandons||0),winStreak:Number(s?.win_streak||0),bestStreak:Number(s?.best_streak||0),totalConquests:Number(s?.total_conquests||0),totalArmiesDestroyed:Number(s?.total_armies_destroyed||0),totalTurns:Number(s?.total_turns||0)},rank:r,rankingPosition:Number(pos?.c||0)+1,achievements:ach.results||[]});}
async function apiRanking(req,env){const url=new URL(req.url),limit=Math.max(1,Math.min(100,Number(url.searchParams.get('limit')||50)));const rows=await env.DB.prepare(`SELECT u.id,u.nick,s.points,s.games,s.wins,s.win_streak FROM user_stats s JOIN users u ON u.id=s.user_id ORDER BY s.points DESC,s.wins DESC,s.games ASC,u.created_at ASC LIMIT ?`).bind(limit).all();return json({ok:true,ranking:(rows.results||[]).map((x,i)=>({position:i+1,id:x.id,nick:x.nick,points:Number(x.points),games:Number(x.games),wins:Number(x.wins),winStreak:Number(x.win_streak),rank:rankFor(Number(x.points))}))});}
async function apiHistory(req,env,user){const url=new URL(req.url),limit=Math.max(1,Math.min(100,Number(url.searchParams.get('limit')||50)));const rows=await env.DB.prepare('SELECT * FROM match_history WHERE user_id=? ORDER BY finished_at DESC LIMIT ?').bind(user.id,limit).all();return json({ok:true,history:(rows.results||[]).map(h=>({...h,playersCount:h.players_count,opponentNames:JSON.parse(h.opponent_names||'[]'),pointsDelta:h.points_delta,rankAfter:h.rank_after,finishedAt:h.finished_at,roomName:h.room_name}))});}

function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function roll(n){return Array.from({length:n},()=>1+Math.floor(Math.random()*6));}
function adjacent(a,b){return !!ADJ[a]?.includes(b);}
function reinforcements(state,userId){const owned=TERRITORIES.filter(t=>state.territories[t.id].owner===userId);let n=Math.max(3,Math.floor(owned.length/3));for(const [cid,c] of Object.entries(CONTINENTS)){const ts=TERRITORIES.filter(t=>t.continent===cid);if(ts.every(t=>state.territories[t.id].owner===userId))n+=c.bonus;}return n;}
function continentOwned(state,userId,cid){return TERRITORIES.filter(t=>t.continent===cid).every(t=>state.territories[t.id].owner===userId);}
function objectiveWinner(state,p){const owned=TERRITORIES.filter(t=>state.territories[t.id].owner===p.id).length,o=state.objectives[p.id];if(owned===TERRITORIES.length)return true;if(!o)return false;if(o.type==='territories')return owned>=o.count;if(o.type==='continents')return o.list.every(cid=>continentOwned(state,p.id,cid));if(o.type==='continents_any_extra')return o.list.every(cid=>continentOwned(state,p.id,cid))&&Object.keys(CONTINENTS).filter(cid=>!o.list.includes(cid)).filter(cid=>continentOwned(state,p.id,cid)).length>=o.extra;if(o.type==='eliminate'){const target=state.players.find(x=>x.color===o.targetColor);return !!target?.eliminated;}return false;}
function checkWinner(state){const active=state.players.filter(p=>!p.eliminated);if(active.length===1)return active[0].id;for(const p of active)if(objectiveWinner(state,p))return p.id;return null;}
function checkElims(state){for(const p of state.players){if(p.eliminated)continue;if(!TERRITORIES.some(t=>state.territories[t.id].owner===p.id)){p.eliminated=true;const h=state.hands[p.id]||[];state.discardPile.push(...h);state.hands[p.id]=[];state.log.push(`${p.name} foi eliminado da batalha.`);}}}
function stateSafeObjectivePool(players){return OBJECTIVE_POOL.slice();}
function makeObjective(state,p,source){let pool=Array.isArray(source)&&source.length?source:OBJECTIVE_POOL.slice();if(!pool.length)pool=OBJECTIVE_POOL.slice();let o=structuredClone(pool[Math.floor(Math.random()*pool.length)]);if(o.type==='eliminate'){const targets=state.players.filter(x=>x.id!==p.id&&x.color);const target=targets[Math.floor(Math.random()*Math.max(1,targets.length))];o.targetColor=target?.color||'';o.text=o.text.replace('{COLOR}',target?.name||'General');}return o;}
function initGame(room){const players=room.players.map(p=>({...p,id:p.id,connId:p.id,eliminated:false,conqueredThisTurn:false}));const ids=shuffle(TERRITORIES.map(t=>t.id));const terr={};ids.forEach((tid,i)=>terr[tid]={owner:players[i%players.length].id,armies:1});const setup={};const start=STARTING_ARMIES[players.length]||20;for(const p of players){const owned=Object.values(terr).filter(x=>x.owner===p.id).length;setup[p.id]=Math.max(0,start-owned);}const objectivePool=stateSafeObjectivePool(players);const objectiveDeck=shuffle(objectivePool.slice());const objectives={};players.forEach((p,i)=>objectives[p.id]=makeObjective({players},p,[objectiveDeck[i%objectiveDeck.length]]));const state={roomId:room.id,roomName:room.name,maxPlayers:room.maxPlayers,hostConnId:room.hostConnId,players,territories:terr,turnIndex:0,turnNumber:1,phase:'setup',setupRemaining:setup,reinforcementsRemaining:0,objectives,deck:[],discardPile:[],hands:{},airAttackCards:{},cardTradeCount:0,usedFortifyTerritories:[],pendingConquestTransfer:null,lastAttackAt:{},lastCombat:null,playerStats:Object.fromEntries(players.map(p=>[p.id,{conquests:0,armiesDestroyed:0}])),log:['Distribuição inicial iniciada.'],winner:null,resultRecorded:false,startedAt:now(),updatedAt:now()};for(const p of players)state.hands[p.id]=[];state.deck=shuffle(TERRITORIES.map(t=>({id:`card_${t.id}`,territoryId:t.id,name:t.name,symbol:null})));return state;}
function drawCard(state,id){if(!state.deck.length){if(!state.discardPile.length)return null;state.deck=shuffle(state.discardPile.splice(0));}const c=state.deck.pop();c.symbol=CARD_SYMBOLS[Math.floor(Math.random()*CARD_SYMBOLS.length)];state.hands[id].push(c);return c;}
function validSet(cards){if(cards.length!==3)return false;const s=cards.map(c=>c.symbol);return s.every(x=>x===s[0])||new Set(s).size===3;}
function tradeValue(state){const n=Number(state.cardTradeCount||0);return n<6?TRADE_VALUES[n]:15+(n-5)*5;}
function advanceSetup(state){if(Object.values(state.setupRemaining).every(v=>v<=0)){state.phase='ataque';state.turnIndex=0;state.log.push('Distribuição concluída — começa a fase de ataque!');return;}for(let i=1;i<=state.players.length;i++){const idx=(state.turnIndex+i)%state.players.length;if((state.setupRemaining[state.players[idx].id]||0)>0){state.turnIndex=idx;break;}}}
function endTurn(state){const p=state.players[state.turnIndex];if(p?.conqueredThisTurn){drawCard(state,p.id);p.conqueredThisTurn=false;}state.usedFortifyTerritories=[];let idx=state.turnIndex;for(let i=1;i<=state.players.length;i++){const n=(idx+i)%state.players.length;if(!state.players[n].eliminated){idx=n;break;}}if(idx<=state.turnIndex)state.turnNumber++;state.turnIndex=idx;const cp=state.players[idx];state.phase=state.turnNumber===1?'ataque':'reforco';state.reinforcementsRemaining=state.phase==='reforco'?reinforcements(state,cp.id):0;state.log.push(`Vez de ${cp.name}.`);}
function applyAction(state,a){const p=state.players[state.turnIndex];if(!p||p.id!==a.byConnId||p.eliminated)return null;const t=state.territories;
 if(a.kind==='setupPlace'){if(state.phase!=='setup')return null;const rem=state.setupRemaining[p.id]||0,x=t[a.territoryId];if(!x||x.owner!==p.id||rem<=0)return null;const n=Math.max(1,Math.min(Number(a.amount)||1,rem));x.armies+=n;state.setupRemaining[p.id]-=n;if(state.setupRemaining[p.id]===0)advanceSetup(state);return state;}
 if(a.kind==='reinforce'){if(state.phase!=='reforco'||state.reinforcementsRemaining<=0)return null;const x=t[a.territoryId];if(!x||x.owner!==p.id)return null;const n=Math.max(1,Math.min(Number(a.amount)||1,state.reinforcementsRemaining));x.armies+=n;state.reinforcementsRemaining-=n;return state;}
 if(a.kind==='endReinforcePhase'){if(state.phase!=='reforco'||state.reinforcementsRemaining>0)return null;state.phase='ataque';return state;}
 if(a.kind==='attack'){if(state.phase!=='ataque'||state.pendingConquestTransfer)return null;const from=t[a.fromId],to=t[a.toId];if(!from||!to||from.owner!==p.id||to.owner===p.id||!adjacent(a.fromId,a.toId)||from.armies<2)return null;const last=state.lastAttackAt[p.id]||0;if(now()-last<1000)return null;state.lastAttackAt[p.id]=now();const dice=Math.max(1,Math.min(Number(a.dice)||1,Math.min(3,from.armies-1)));const defDice=Math.min(3,to.armies);const ar=roll(dice).sort((x,y)=>y-x),dr=roll(defDice).sort((x,y)=>y-x);let al=0,dl=0;for(let i=0;i<Math.min(ar.length,dr.length);i++)ar[i]>dr[i]?dl++:al++;from.armies=Math.max(1,from.armies-al);const before=to.armies;const after=Math.max(0,before-dl),conquered=after===0;to.armies=conquered?1:Math.max(1,after);state.playerStats[p.id].armiesDestroyed+=dl;if(conquered){state.playerStats[p.id].conquests++;to.owner=p.id;p.conqueredThisTurn=true;state.pendingConquestTransfer={fromId:a.fromId,toId:a.toId};}state.lastCombat={fromId:a.fromId,toId:a.toId,atkRolls:ar,defRolls:dr,atkLoss:al,defLoss:dl,conquered,ts:now()};state.log.push(`${p.name} atacou ${T[a.toId].name}: ${ar.join(',')} x ${dr.join(',')}${conquered?' — território conquistado!':''}`);checkElims(state);return state;}
 if(a.kind==='conquestTransfer'){if(state.phase!=='ataque')return null;const q=state.pendingConquestTransfer;if(!q||q.fromId!==a.fromId||q.toId!==a.toId)return null;const from=t[q.fromId],to=t[q.toId];if(!from||!to||from.owner!==p.id||to.owner!==p.id)return null;const max=Math.min(3,Math.max(0,from.armies-1));if(max<1)return null;const requested=Number(a.amount);if(!Number.isFinite(requested))return null;const n=Math.max(1,Math.min(Math.floor(requested),max));from.armies-=n;to.armies+=n;state.pendingConquestTransfer=null;state.lastCombat={...(state.lastCombat||{}),conquestTransfer:n,conquestTransferOnly:true,ts:now()};return state;}
 if(a.kind==='airAttack'){if(state.phase!=='ataque'||state.pendingConquestTransfer||(state.airAttackCards[p.id]||0)<=0)return null;const to=t[a.toId];if(!to||to.owner===p.id)return null;const last=state.lastAttackAt[p.id]||0;if(now()-last<1000)return null;state.lastAttackAt[p.id]=now();const destroyed=Number(to.armies||0),fromId=TERRITORIES.find(x=>t[x.id].owner===p.id&&x.id!==a.toId)?.id||null;state.playerStats[p.id].armiesDestroyed+=destroyed;state.playerStats[p.id].conquests++;to.owner=p.id;to.armies=1;p.conqueredThisTurn=true;state.pendingConquestTransfer=null;state.airAttackCards[p.id]--;state.lastCombat={fromId,toId:a.toId,atkRolls:[],defRolls:[],atkLoss:0,defLoss:destroyed,conquered:true,airAttack:true,ts:now()};state.log.push(`${p.name} lançou um Ataque Aéreo contra ${T[a.toId].name}.`);checkElims(state);return state;}
 if(a.kind==='endAttackPhase'){if(state.phase!=='ataque'||state.pendingConquestTransfer)return null;state.phase='fortificacao';state.usedFortifyTerritories=[];return state;}
 if(a.kind==='fortify'){if(state.phase!=='fortificacao')return null;const from=t[a.fromId],to=t[a.toId],used=state.usedFortifyTerritories||[];if(!from||!to||from.owner!==p.id||to.owner!==p.id||!adjacent(a.fromId,a.toId)||used.includes(a.fromId)||used.includes(a.toId)||from.armies<2)return null;const n=Math.max(1,Math.min(Number(a.amount)||1,from.armies-1));from.armies-=n;to.armies+=n;state.usedFortifyTerritories.push(a.fromId,a.toId);return state;}
 if(a.kind==='endTurn'){if(state.phase!=='fortificacao'&&state.phase!=='ataque')return null;if(state.pendingConquestTransfer)return null;endTurn(state);return state;}
 if(a.kind==='exchangeCards'){if(state.phase!=='reforco')return null;const hand=state.hands[p.id]||[],ids=Array.isArray(a.cardIds)?a.cardIds:[];if(ids.length!==3||new Set(ids).size!==3)return null;const cards=ids.map(id=>hand.find(c=>c.id===id));if(cards.some(x=>!x)||!validSet(cards))return null;state.hands[p.id]=hand.filter(c=>!ids.includes(c.id));state.discardPile.push(...cards);if(cards.every(c=>c.symbol===AIR)){state.airAttackCards[p.id]=(state.airAttackCards[p.id]||0)+1;state.lastCardExchange={by:p.id,reward:0,airAttackCreated:1,ts:now()};return state;}const reward=tradeValue(state);state.cardTradeCount++;state.reinforcementsRemaining+=reward;for(const c of cards){if(t[c.territoryId]?.owner===p.id)t[c.territoryId].armies+=2;}state.lastCardExchange={by:p.id,reward,ts:now()};return state;}
 return null;}

async function recordResults(env,state){if(state.resultRecorded||!state.winner)return;state.resultRecorded=true;const ts=now();const winner=state.winner;for(const p of state.players){const result=p.id===winner?'win':p.eliminated?'loss':'loss';const delta=result==='win'?100:-25;const st=await env.DB.prepare('SELECT * FROM user_stats WHERE user_id=?').bind(p.id).first();if(!st)continue;let streak=Number(st.win_streak||0),best=Number(st.best_streak||0);streak=result==='win'?streak+1:0;best=Math.max(best,streak);const points=Math.max(0,Number(st.points||0)+delta);const rank=rankFor(points);await env.DB.prepare('UPDATE user_stats SET points=?,games=games+1,wins=wins+?,losses=losses+?,win_streak=?,best_streak=?,total_conquests=total_conquests+?,total_armies_destroyed=total_armies_destroyed+?,total_turns=total_turns+? WHERE user_id=?').bind(points,result==='win'?1:0,result==='loss'?1:0,streak,best,Number(state.playerStats[p.id]?.conquests||0),Number(state.playerStats[p.id]?.armiesDestroyed||0),Number(state.turnNumber||0),p.id).run();const opponents=state.players.filter(x=>x.id!==p.id).map(x=>x.name);await env.DB.prepare('INSERT INTO match_history(id,user_id,room_id,room_name,result,finished_at,players_count,opponent_names,points_delta,rank_after) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(uuid(),p.id,state.roomId,state.roomName,result,ts,state.players.length,JSON.stringify(opponents),delta,rank.name).run();}
 const checks=await env.DB.prepare('SELECT u.id,s.* FROM user_stats s JOIN users u ON u.id=s.user_id WHERE s.user_id IN ('+state.players.map(()=>'?').join(',')+')').bind(...state.players.map(p=>p.id)).all();for(const s of checks.results||[]){const wins=Number(s.wins),games=Number(s.games),points=Number(s.points),ach=[];if(games>=1)ach.push('first_battle');if(wins>=1)ach.push('first_victory');if(wins>=5)ach.push('five_victories');if(wins>=10)ach.push('ten_victories');if(Number(s.win_streak)>=3)ach.push('streak_three');if(points>=100)ach.push('hundred_points');if(points>=1000)ach.push('thousand_points');if(rankFor(points).id==='marechal')ach.push('marshal');for(const a of ach)await env.DB.prepare('INSERT OR IGNORE INTO user_achievements(user_id,achievement_id,unlocked_at) VALUES(?,?,?)').bind(s.id,a,ts).run();}}

export class UORRoom {
 constructor(state,env){this.state=state;this.env=env;this.sockets=new Map();this.state.blockConcurrencyWhile(async()=>{this.room=await this.state.storage.get('room')||null;this.game=await this.state.storage.get('game')||null;});}
 async persist(){await this.state.storage.put('room',this.room);await this.state.storage.put('game',this.game);}
 async roomForPublic(){return this.room?{id:this.room.id,name:this.room.name,maxPlayers:this.room.maxPlayers,hostConnId:this.room.hostConnId,players:this.room.players,gameActive:!!this.game,updatedAt:now()}:null;}
 broadcast(msg){const raw=JSON.stringify(msg);for(const ws of this.sockets.values())try{ws.send(raw)}catch{}}
 async fetch(req){const url=new URL(req.url),path=url.pathname; if(path.endsWith('/internal/init')){const b=await body(req);this.room={...b,hostConnId:b.hostConnId||b.players?.[0]?.id||null};await this.persist();return json({ok:true});}
  if(path.endsWith('/internal/join')){if(this.game)return json({ok:false,error:'A partida já começou.'},409);const b=await body(req),uid=b.userId;if(!this.room)return json({ok:false,error:'Sala inexistente.'},404);if(this.room.players.some(p=>p.id===uid))return json({ok:true,room:await this.roomForPublic(),assignedColor:this.room.players.find(p=>p.id===uid).color});if(this.room.players.length>=this.room.maxPlayers)return json({ok:false,error:'Sala cheia, general.'},409);const used=this.room.players.map(p=>p.color),color=COLORS.includes(b.color)&&!used.includes(b.color)?b.color:COLORS.find(c=>!used.includes(c))||COLORS[0];this.room.players.push({id:uid,connId:uid,name:String(b.name||'General').slice(0,24),color,eliminated:false});await this.persist();this.broadcast({type:'room_state',room:await this.roomForPublic()});return json({ok:true,room:await this.roomForPublic(),assignedColor:color});}
  if(path.endsWith('/internal/leave')){const uid=req.headers.get('x-uor-user');if(!this.room)return json({ok:true,deleted:true});this.sockets.get(uid)?.close(1000,'leave');this.sockets.delete(uid);this.room.players=this.room.players.filter(p=>p.id!==uid);if(!this.room.players.length){this.room=null;this.game=null;await this.persist();return json({ok:true,deleted:true});}if(this.room.hostConnId===uid)this.room.hostConnId=this.room.players[0].id;if(this.game)this.game.players.find(p=>p.id===uid)&&(this.game.players.find(p=>p.id===uid).eliminated=true);await this.persist();this.broadcast({type:'room_state',room:await this.roomForPublic()});return json({ok:true,room:await this.roomForPublic()});}
  if(path==='/ws' || path.startsWith('/ws')){if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket required',{status:426});const uid=req.headers.get('x-uor-user');if(!uid||!this.room)return new Response('Unauthorized',{status:401});const publicRoom=await this.roomForPublic();const pair=new WebSocketPair(),client=pair[0],server=pair[1];server.accept();this.sockets.set(uid,server);server.addEventListener('message',e=>this.onMessage(uid,server,e));server.addEventListener('close',()=>this.onClose(uid,server));server.send(JSON.stringify({type:'room_state',room:publicRoom}));if(this.game)server.send(JSON.stringify({type:'game_state_sync',state:this.game}));return new Response(null,{status:101,webSocket:client});}
  return json({ok:false,error:'Not found'},404);
 }
 async onClose(uid,ws){if(this.sockets.get(uid)!==ws)return;this.sockets.delete(uid);if(!this.room)return;if(!this.game){this.room.players=this.room.players.filter(p=>p.id!==uid);if(!this.room.players.length){const rid=this.room.id;this.room=null;await this.persist();await this.env.DB.prepare('DELETE FROM rooms WHERE id=?').bind(rid).run();return;}if(this.room.hostConnId===uid)this.room.hostConnId=this.room.players[0].id;await this.persist();await syncRoomRow(this.env,this.room.id,await this.roomForPublic());this.broadcast({type:'room_state',room:await this.roomForPublic()});return;}const p=this.game.players.find(x=>x.id===uid);if(p&&!p.eliminated&&this.game.hostConnId===uid){const next=this.game.players.find(x=>!x.eliminated&&this.sockets.has(x.id));if(next){this.game.hostConnId=next.id;this.room.hostConnId=next.id;this.game.log.push(`${next.name} assumiu o comando da batalha.`);await this.persist();await syncRoomRow(this.env,this.room.id,await this.roomForPublic());this.broadcast({type:'host_migrated',newHostConnId:next.id});this.broadcast({type:'game_state_sync',state:this.game});}}}
 async onMessage(uid,ws,e){let m;try{m=JSON.parse(e.data)}catch{return}if(!m?.type)return;if(m.type==='sync_request'){if(this.game)ws.send(JSON.stringify({type:'room_relay',roomId:this.room.id,payload:{type:'game_state_sync',state:this.game}}));else if(this.room)ws.send(JSON.stringify({type:'room_relay',roomId:this.room.id,payload:{type:'room_state',room:await this.roomForPublic()}}));return;}if(m.type==='room_chat'){const entry={name:this.room.players.find(p=>p.id===uid)?.name||'General',color:this.room.players.find(p=>p.id===uid)?.color||COLORS[0],text:String(m.entry?.text||'').trim().slice(0,400),ts:now()};if(!entry.text)return;this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'room_chat',entry}});return;}
  if(m.type==='game_chat'){if(!this.game)return;const p=this.game.players.find(x=>x.id===uid);if(!p||p.eliminated)return;const text=String(m.entry?.text||'').trim().slice(0,400);if(!text)return;const entry={name:p.name,color:p.color,text,ts:now()};this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'game_chat',entry}});return;}
  if(m.type==='start_game'){if(uid!==this.room.hostConnId||this.room.players.length!==this.room.maxPlayers||this.game)return;this.game=initGame(this.room);this.room.gameActive=true;await this.persist();await syncRoomRow(this.env,this.room.id,await this.roomForPublic());this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'game_start',state:this.game}});return;}
  if(m.type==='air_attack_request'){if(!this.game)return;const a={...(m.action||{}),byConnId:uid};const next=applyAction(this.game,a);if(!next){ws.send(JSON.stringify({type:'room_relay',roomId:this.room.id,payload:{type:'game_action_rejected',reason:'Ataque aéreo recusado pelo servidor.'}}));return;}this.game=next;this.game.winner=checkWinner(this.game);if(this.game.winner&&!this.game.resultRecorded)await recordResults(this.env,this.game);await this.persist();this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'air_attack_visual',action:a,ts:now()}});this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'game_state_sync',state:this.game}});return;}
  if(m.type==='game_action'){if(!this.game)return;const a={...(m.action||{}),byConnId:uid};const next=applyAction(this.game,a);if(!next){ws.send(JSON.stringify({type:'room_relay',roomId:this.room.id,payload:{type:'game_action_rejected',reason:'Ação recusada pelo servidor. Confira a fase, o alvo e aguarde a sincronização.'}}));return;}this.game=next;this.game.winner=checkWinner(this.game);if(this.game.winner&&!this.game.resultRecorded)await recordResults(this.env,this.game);await this.persist();this.broadcast({type:'room_relay',roomId:this.room.id,payload:{type:'game_state_sync',state:this.game}});}
 }
}

async function route(req,env){try{return await routeInner(req,env);}catch(e){return json({ok:false,error:'Erro interno do servidor.',detail:String(e?.message||e)},500);}}
async function routeInner(req,env){const url=new URL(req.url),p=url.pathname;if(p==='/api/auth/me')return apiAuthMe(req,env);if(p==='/api/auth/register'&&req.method==='POST')return apiAuthRegister(req,env);if(p==='/api/auth/login'&&req.method==='POST')return apiAuthLogin(req,env);if(p==='/api/auth/logout'&&req.method==='POST')return apiAuthLogout(req,env);const user=await authUser(req,env);if(!user)return json({ok:false,error:'Faça login para continuar.'},401);
 if(p==='/api/profile')return apiProfile(req,env,user);if(p==='/api/ranking')return apiRanking(req,env);if(p==='/api/history')return apiHistory(req,env,user);if(p==='/api/chat')return apiChat(req,env,user);if(p==='/api/rooms'&&req.method==='GET')return apiRooms(req,env);if(p==='/api/rooms'&&req.method==='POST')return apiCreateRoom(req,env,user);let m=p.match(/^\/api\/rooms\/([^/]+)\/(join|leave)$/);if(m&&req.method==='POST')return m[2]==='join'?apiJoinRoom(req,env,user,m[1]):apiLeaveRoom(req,env,user,m[1]);return json({ok:false,error:'Endpoint não encontrado.'},404);}

export default {async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname.startsWith('/ws/rooms/')){const user=await authUser(req,env);if(!user)return new Response('Unauthorized',{status:401});const id=decodeURIComponent(url.pathname.split('/').pop());const d=await getRoomDO(env,id);const headers=new Headers(req.headers);headers.set('x-uor-user',user.id);return d.fetch(new Request(req,{headers}));}if(url.pathname.startsWith('/api/'))return route(req,env);return env.ASSETS.fetch(req);}};
